application/views/addadmin.php
application/views/superadmin/addcomputershop.php
assets/css/register.css

added Superadmin Navbar

---

application/views/superadmin/addadmin.php
assets/css/register.css

updated nav bar text color from white to orange

navbar_Branch

---

application/views/admin/scanqr.php

Ang cam kay awkward tanawon kay bali so i mirrored the camera hope ma dawat :D

mirrored awkward  Camera

---

application/views/userprof_Settings.php

added findn user details

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/computerbform.php
assets/css/bform.css
assets/js/bform.js

not polished yet sir, puhon mayng lawas

computer booking form UI

---

application/controllers/LogicalController.php
application/models/MainModel.php

back end finished

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/accountSettings.php
application/views/findnRegister.php
assets/css/accountSettings.css
assets/css/findnRegister.css
assets/js/findnRegister.js

New registration page. Need backend ASAP

New Registration Page: DUBLIN

---

application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/computershopdetails.php
application/views/admin/computertype.php
assets/admin/css/computertype.css
assets/js/ctype.js

-add/insert computer type 
-delete computer type
-minor changes of computer details

Add computer type

---

assets/js/adminlist.js
assets/js/registerP.js

updated finders and admins username requirements 
min length 8
max length 16

username requirements adjusted

---

db_backup/findn-3-16-22.sql

-added two columns for computer type(computer image and status)
-relationship for computer type to computer shop

updated database for computer type

---

application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/computertypelist.php
application/views/admin/updatecomptype.php

-population of computer types
-adding of computer types
-deletion of compuiter types
-updating of computer types

COMPUTER TYPE FEATURES FOR ADMIN

---

application/views/admin/computertypelist.php

change input from specifications to text area

textarea for specifications

---

application/views/requestBook.php
assets/css/requestBook.css

Fixed cursor pointer and background color for input tags

Fixed input tag to cursor pointer & backColors

---

application/views/admin/viewComputerType.php

delete computer type

---

application/config/config.php
application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/computertypelist.php
application/views/admin/postEvents.php
assets/admin/css/postevents.css

Working api's
-add posts
-delete posts
-edit posts
-view all posts
Slight modifications of computertype lists
-added delete button functionality

Computer shop on posting their announcement/events

---

application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/viewPost.php

oks na module for post and comments :D

update on comments of sessioned users

---

application/config/config.php
application/config/routes.php
application/controllers/LogicalController.php
application/models/MainModel.php

List of pending Bookings Request
List Of Accepted Bookings
Select Booking
View Details of Booking
Accept/Denied Pending Booking

booking requests lists

---

application/models/MainModel.php

Service Type Fee Fix

---

application/config/config.php
application/views/finderBookingList.php
application/views/finders/navbar-query.php
application/views/finders/navbar.php
application/views/findersGCashPayment.php
application/views/findersTransactionDetail.php
application/views/viewShop.php
application/views/viewmap.php
assets/css/findersBookings.css
assets/css/navbar.css
assets/css/requestBook.css
assets/css/viewShop.css
assets/js/navbar.js
assets/js/viewShop.js

DUBLIN| Fixed Navbar bug, Bookings container, viewShop Navbar

DUBLIN| Fixed Navbar bug, Bookings container, viewShop Navbar

---

application/config/config.php
application/config/routes.php
application/controllers/Main_Controller.php
application/views/finders/navbar-query.php
application/views/finders/navbar.php
application/views/findersNotification.php
assets/css/findersNotification.css
assets/css/navbar.css
assets/js/findersNotification.js

Built a new Notification page for our finders. Ye

DUBLIN| New Notification page

---

application/views/requestBook.php
assets/js/viewShop.js

Fix modal shop | DUBLIN

---

application/views/requestBook.php
assets/js/navbar.js
assets/js/viewShop.js

Fix navbar error

---

application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/views/admin/template/adminHeader.php
assets/admin/css/adminHeader.css
assets/admin/js/adminHeader.js

Disregard ang changes sa Main_controller sa admin_bookings() kay akoa rana ge try ma ang new header ug sidebar

Sidebar & header for admin |DUBLIN

---

application/config/routes.php
application/controllers/LogicalController.php
application/models/MainModel.php

view all booking requests from shopadmin

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/admin/shopAdminBookings.php
application/views/admin/template/adminHeader.php
assets/css/adminHeader.css
assets/css/shopAdminBookings.css
assets/js/adminHeader.js

Unresolved bugs in sidebar admin, MAYBE will recreate sidebar

FIX-Admin-Sidebar minimal, Major bugs stil unresolved |DUBLIN

---

application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/shopAdminBookings.php

waiting list done
all list of bookings done

anadawan for shop admin booking list

---

application/views/admin/shopAdminScanQR.php
assets/css/shopAdminScanQR.css

Merge these few adjustment first before back-end logic

FIX few adjustments

---

application/controllers/Main_Controller.php
application/views/admin/template/adminHeader.php
assets/css/adminHeader.css
assets/js/adminHeader.js

Final Shop Admin Header |DUBLIN

---

application/views/admin/shopAdminBookings.php
assets/css/shopAdminBookings.css

Static Modal. Ready for back-end. Its 5:19 AM sheeesshh

Modal for list of Transactions | DUBLIN

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/admin/shopAdminDashboard.php
assets/css/shopAdminDashboard.css

DASHBOARD UI ready for back-end

Dashboard Admin |DUBLIN

---

application/config/routes.php
application/controllers/LogicalController.php
application/models/MainModel.php
application/views/findnRegister.php
assets/css/findnRegister.css
assets/js/findnRegister.js

have migrated and applied the validation for the new register

new register validation

---

application/config/routes.php
application/controllers/LogicalController.php
application/controllers/Main_Controller.php
application/models/MainModel.php
application/views/admin/shopAdminBookings.php

anadawan for admin booking list

---

application/views/findnRegister.php

update validation fix

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/admin/shopAdminComputerType.php
assets/css/shopAdminComputerType.css
assets/js/adminHeader.js
assets/js/shopAdminComputerType.js

Computer type UI ready for back-end

Computer Type UI | DUBLIN

---

application/views/admin/shopAdminComputerType.php
assets/css/shopAdminComputerType.css

Co-authored-by: JunkyDubs <barbecue2304@users.noreply.github.com>

fixing with dubs computertype

---

application/views/admin/shopAdminComputerType.php
assets/css/shopAdminComputerType.css

Fix view button with image preview

Fix View type button |DUBLIN

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/accountSettings.php
application/views/admin/shopAdminAccountSettings.php
application/views/findnRegister.php
assets/css/findnRegister.css
assets/css/shopAdminAccountSettings.css

Minor bugs to account settings

Fix account settings stil has minor bugs |DUBLIN

---

application/controllers/Main_Controller.php
application/views/accountSettings.php
application/views/admin/shopAdminAccountSettings.php
application/views/admin/shopAdminDashboard.php
assets/css/adminHeader.css
assets/css/shopAdminAccountSettings.css

Fix account settings |DUBLIN

---

application/views/admin/template/adminHeader.php
assets/css/adminHeader.css

Header Notification Dropdown |DUBLIN

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/admin/shopAdminFeed.php
assets/css/shopAdminFeed.css
assets/js/shopAdminFeed.js

Shop Admin FEED |DUBLIN

---

application/controllers/LogicalController.php
application/views/admin/shopAdminBookings.php
application/views/admin/template/adminHeader.php

-when there are no notifications, hide badge
-hide overdue button on list of all buttons

minor changes for admin bookings and notifications

---

application/controllers/Main_Controller.php
application/views/admin/shopAdminReports.php
assets/css/shopAdminReports.css

FEAT| SHOP ADMIN REPORTS |DUBLIN

---

application/views/admin/shopAdminReports.php
application/views/admin/template/adminHeader.php
assets/css/shopAdminReports.css

Fixed minor bugs and added shop admin reports to sidebar menu

Fixed minor bugs and added shop admin reports to sidebar menu |DUBLIN

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/findersHome.php
assets/css/findersHome.css
assets/css/navbar.css

FEAT: Newly designed homepage for finders |DUBLIN

---

application/views/finders/navbar-query.php
application/views/finders/navbar.php
application/views/viewShop.php
assets/css/viewShop.css

Finders submit ratings and review

FEAT/ Finders Submit Review |DUBLIN

---

assets/css/findersHome.css

Fixed minor bugs in finders home page |DUBLIN

---

application/views/findnRegister.php

Passwordkeyup

---

application/models/MainModel.php
application/views/superadmin/adminlist.php
application/views/superadmin/listofcomputershop.php

checking up the super admin side nya naa koy nakitan di mao so i fixed it please pull

fixing the explosions

---

application/models/MainModel.php
application/views/makepdf.php
application/views/superadmin/adminlist.php
application/views/superadmin/reports.php
assets/css/style.css

Reportsupdate

---

application/config/routes.php
application/controllers/Main_Controller.php
application/views/superadmin/superAdminDashBoard.php
assets/css/superAdminDashBoard.css
assets/js/superAdminDashBoard.js

superadmin |DUBLIN
